[project]
name = "wesad"
version = "0.2.0"
description = "A collection of utilities for the WESAD dataset as Python package and scripts."
readme = "README.md"
authors = [
    { name = "ArcaLunar", email = "arca@connect.hku.hk" }
]
requires-python = ">=3.12"
dependencies = [
    "loguru",
    "numpy",
    "pydantic",
    "requests",
    "rich",
    "scipy",
]

[project.scripts]
wesad-download = "wesad.download:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
