[project]
name = "wesad"
version = "0.1.0"
description = "A collection of utilities for the WESAD dataset as Python package and scripts."
readme = "README.md"
authors = [
    { name = "ArcaLunar", email = "arca@connect.hku.hk" }
]
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.5.2",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "rich>=15.0.0",
]

[project.scripts]
wesad-download = "wesad.download:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
